authentication/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.authenticationView, name='authentication'),
    path('login/', views.loginView, name='login'),
    path('edit/<int:pk>', views.editView, name='edit'),
    path('change-password/', views.ChangePasswordView.as_view(), name='change-password'),
    path('delete-avatar/', views.deleteAvatar, name='delete-avatar'),
    path('logout/', views.logoutView, name='logout'),
]

main/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('group/<str:groupName>/', views.groupInfo, name='group-info'),
    path('teachers/', views.allTeachers, name='teachers'),
    path('students/', views.allStudents, name='students'),
    path('teachers/<str:username>/', views.teacherInfo, name='teacher-info'),
    path('students/<str:username>/', views.studentInfo, name='student-info'),
    path('join-group/<str:groupName>/', views.joinGroup, name='join-group'),
    path('leave-group/<str:groupName>/', views.leaveGroup, name='leave-group'),
    path('check-achievement/<int:id>/', views.checkAchievement, name='check-achievement'),
    path('delete-achievement/<int:id>/', views.deleteAchievement, name='delete-achievement'),
    path('authentication/', include('authentication.urls'))
]

studentsprojects/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


handler404 = "studentsprojects.views.page404"
handler500 = "studentsprojects.views.page500"

authentication/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    avatar = models.FileField(upload_to='avatars', null=True, blank=True)
    username = models.CharField(max_length = 17, unique=True)
    last_name = models.CharField(max_length = 50)
    first_name = models.CharField(max_length = 50)
    patronymic = models.CharField(max_length=17, null=True, blank=True)
    email = models.EmailField(unique=True, default='')
    isTeacher = models.BooleanField(default=False)
    userGroup = models.ManyToManyField('main.Group', default=None)


    def fullName(self):

        return self.last_name + ' ' + self.first_name


    def fullTeacherName(self):
        return self.last_name + " " + self.first_name[0] + ". " + self.patronymic[0] + "."

authentication/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ['username', 'email', 'avatar', 'first_name', 'last_name', 'password1', 'password2']

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] != cd['password2']:
            raise forms.ValidationError('Пароли не совпадают')
        return cd['password2']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if CustomUser.objects.filter(email=email).exists():
            raise forms.ValidationError('Почта уже существует')
        return email

    def clean_username(self):
        if CustomUser.objects.filter(username=self.cleaned_data['username']).exists():
            raise forms.ValidationError('Данный пользователь уже существует')
        return self.cleaned_data['username']

class CustomUserUpdateForm(forms.ModelForm):

    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'avatar', 'first_name', 'last_name']

authentication/views.py
from asyncio.windows_events import NULL
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from authentication.forms import CustomUserCreationForm, CustomUserUpdateForm


def authenticationView(request):
    if request.user.is_authenticated:
        return redirect('home')
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = CustomUserCreationForm()

    return render(request, 'authentication.html', {'form': form})


def loginView(request):
    messageError = ''
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('home')
            else:
                messages.error('Имя пользователя или пароль неверны')
                return redirect('login')
    else:
        form = AuthenticationForm()

    return render(request, 'login.html', {'form': form})


def editView(request, pk):
    if not request.user.is_authenticated:
        return redirect('authentication')
    else:
        if request.user.id != pk:
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        if request.method == 'POST':
            customUserForm = CustomUserUpdateForm(request.POST, request.FILES, instance=request.user)

            if customUserForm.is_valid():
                customUserForm.save()
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        else:
            customUserForm = CustomUserUpdateForm()
        
        return render(request, 'edit.html', {'customUserForm': customUserForm})


class ChangePasswordView(SuccessMessageMixin, PasswordChangeView):

    template_name = 'change-password.html'
    success_message = "Пароль успешно сменен!"
    success_url = reverse_lazy('home')


def deleteAvatar(request):
    if not request.user.is_authenticated:
        return redirect('authentication')
    else:
        if request.user.avatar:
            request.user.avatar.delete()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        else:
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def logoutView(request):
    if not request.user.is_authenticated:
        return redirect('authentication')
    else:
        logout(request)

        return redirect('home')

authentication/templates/authentication.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1"> 
 
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"> 
 
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

	<title>Регистрация</title>
</head>
<body class="auth-body">
    {% if not form.is_valid %}
		<div>
			<form enctype="multipart/form-data" class="auth-form" method="post">
				{% csrf_token %}
				<h1>Регистрация</h1>
				
				<input type="text" name="username" maxlength="100" required id="id_username" placeholder="Ваш логин">
				{% if form.errors.username %}
					<ul class="error-list">
						{{form.errors.username}}
					</ul>
				{% endif %}

                
				<input type="text" name="first_name" maxlength="100" required id="id_first_name" placeholder="Ваше имя">
				{% if form.errors.first_name %}
					<ul class="error-list">
						{{form.errors.first_name}}
					</ul>
				{% endif %}

                
				<input type="text" name="last_name" maxlength="100" required id="id_last_name" placeholder="Ваша фамилия">
				{% if form.errors.last_name %}
					<ul class="error-list">
						{{form.errors.last_name}}
					</ul>
				{% endif %}

				
				<input type="text" name="email" maxlength="100" required id="id_email" placeholder="Ваша эл. почта">
				{% if form.errors.email %}
					<ul class="error-list">
						{{form.errors.email}}
					</ul>
				{% endif %}

				<label for="id_avatar">Выбрать фото профиля:</label>
                    <input type="file" name="avatar" accept="image/*" id="id_avatar">
                    {% if form.errors.avatar %}
                        <ul class="error-list">
                            {{form.errors.avatar}}
                        </ul>
                    {% endif %}

				
				<input type="password" name="password1" maxlength="100" required id="id_password1" placeholder="Придумайте пароль">
				{% if form.errors.password1 %}
					<ul class="error-list">
						{{form.errors.password1}}
					</ul>
				{% endif %}

				
				<input type="password" name="password2" maxlength="100" required id="id_password2" placeholder="Повторите пароль">
				{% if form.errors.password2 %}
					<ul class="error-list">
						{{form.errors.password2}}
					</ul>
				{% endif %}
				
				<input type="submit" name="login" value="Зарегистрироваться">
				<a href="{% url 'login' %}">Уже есть аккаунт?</a>
				<a href="{% url 'home' %}">Вернуться на главную</a>
			</form>
		</div>
    {% endif %}
</div>
</body>
</html>

authentication/templates/change-password.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1"> 
 
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"> 
 
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

	<title>Смена пароля</title>
</head>
<body class="auth-body">
    {% if not form.is_valid %}
		<div>
			<form class="auth-form" method="post">
				{% csrf_token %}
                <h1>Смена пароля</h1>
                <label class="small mb-1" for="id_old_password">Действующий пароль</label>
                <input type="password" name="old_password" autocomplete="current-password" autofocus="" required="" id="id_old_password">			
                
                <label class="small mb-1" for="id_new_password1">Новый пароль</label>
                <input type="password" name="new_password1" autocomplete="new-password" required="" id="id_new_password1">

                <label class="small mb-1" for="id_new_password2">Подтвердите новый пароль</label>
                <input type="password" name="new_password2" autocomplete="new-password" required="" id="id_new_password2"> 
                {% if form.errors.new_password2 %} 
                    <ul class="error-list">
                        {{form.errors.new_password2}}
                    </ul>
                {% endif %}
				<input type="submit" name="login" value="Сменить пароль">
				<a href="{% url 'home' %}">Вернуться на главную</a>
			</form>
		</div>
    {% endif %}
</div>
</body>
</html>

authentication/templates/edit.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1"> 
 
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"> 
 
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

	<title>Редактирование профиля</title>
</head>

<body class="auth-body">
    {% if not form.is_valid %}
		<div>
			<form enctype="multipart/form-data" class="auth-form" method="post">
				{% csrf_token %}
				<h1 class="">Редактирование</h1>

                <label for="id_username">Ваше имя пользователя:</label>
				<input type="text" name="username" maxlength="17" required id="id_username" value="{{request.user.username}}">
				{% if form.errors.username %}
					<ul class="error-list">
						{{form.errors.username}}
					</ul>
				{% endif %}

                <label for="id_username">Ваша электронная почта:</label>
				<input type="text" name="email" maxlength="250" required id="id_email" value="{{request.user.email}}">
				{% if form.errors.email %}
					<ul class="error-list">
						{{form.errors.email}}
					</ul>
				{% endif %}

                <label for="id_username">Ваше имя:</label>
				<input type="text" name="first_name" maxlength="50" required id="id_first_name" value="{{request.user.first_name}}">
				{% if form.errors.first_name %}
					<ul class="error-list">
						{{form.errors.first_name}}
					</ul>
				{% endif %}

                <label for="id_username">Ваша фамилия:</label>
                <input type="text" name="last_name" maxlength="50" required id="id_last_name" value="{{request.user.last_name}}">
				{% if form.errors.last_name %}
					<ul class="error-list">
						{{form.errors.last_name}}
					</ul>
				{% endif %}

				<label for="id_avatar">Поменять фото профиля:</label>
				<input type="file" name="avatar" accept="image/*" id="id_avatar">
				{% if form.errors.avatar %}
					<ul class="error-list">
						{{form.errors.avatar}}
					</ul>
				{% endif %}

				<input type="submit" name="login" value="Сохранить изменения">
				<a href="{% url 'change-password' %}">Сменить пароль</a>
				<a href="{% url 'logout' %}">Выйти из аккаунта</a><br>
				<a href="{% url 'home' %}">Вернуться на главную</a>
			</form>
		</div>
    {% endif %}
</div>
</div>
</body>
</html>

authentication/templates/login.html
{% load static %} 
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1"> 
 
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"> 
 
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
	<title>Вход в аккаунт</title>
</head>
<body class="auth-body">
	<form class="auth-form" method="post">
		{% csrf_token %}
		<h1>Вход в аккаунт</h1>
		<label for="id_username">Ваше имя пользователя:</label>
		<input type="text" name="username" autofocus autocapitalize="none" autocomplete="username" maxlength="150" required id="id_username">
		
		<label for="id_password">Ваш пароль:</label>
		<input type="password" name="password" autocomplete="current-password" required id="id_password">
		{% if form.errors %}
		    <ul class="error-list">
		    	<li>Имя пользователя или пароль неверны</li>
		    </ul>
		{% endif %}
		<input type="submit" name="login" value="Войти">
		<a href="{% url 'authentication' %}">Еще нет аккаунта?</a>
		<a href="{% url 'home' %}">Вернуться на главную</a>
	</form>	
</body>
</html>