main/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('group/<str:groupName>/', views.groupInfo, name='group-info'),
    path('teachers/', views.allTeachers, name='teachers'),
    path('students/', views.allStudents, name='students'),
    path('teachers/<str:username>/', views.teacherInfo, name='teacher-info'),
    path('students/<str:username>/', views.studentInfo, name='student-info'),
    path('join-group/<str:groupName>/', views.joinGroup, name='join-group'),
    path('leave-group/<str:groupName>/', views.leaveGroup, name='leave-group'),
    path('check-achievement/<int:id>/', views.checkAchievement, name='check-achievement'),
    path('delete-achievement/<int:id>/', views.deleteAchievement, name='delete-achievement'),
    path('authentication/', include('authentication.urls'))
]

studentsprojects/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


handler404 = "studentsprojects.views.page404"
handler500 = "studentsprojects.views.page500"

main/models.py
from django.db import models
from django.urls import reverse

from authentication.models import CustomUser


class Group(models.Model):
    groupName = models.CharField(max_length=15, unique=True)
    groupTeacher = models.ForeignKey(CustomUser, on_delete=models.DO_NOTHING)
    groupYearAdmission = models.DateField()


    def __str__(self):

        return self.groupName

    def get_url(self):
        
        return reverse('group-info', kwargs={'groupName': self.groupName})

    def get_teacher(self):
        
        return reverse('teacher-info', kwargs={'username': self.groupTeacher.username})


class Achievement(models.Model):
    person = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    achievement = models.FileField(upload_to='diplomas')
    name = models.CharField(max_length=127, default='')

    def __str__(self):
        return self.person.fullName() + " - " + self.name

main/forms.py
from django import forms
from django.forms import ModelForm
from .models import Achievement

class AchievementForm(ModelForm):

    class Meta:
        model = Achievement
        fields = ['achievement', 'name']

main/views.py
from django.http import FileResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render

from authentication.models import CustomUser
from .forms import AchievementForm

from .models import Achievement, Group


def home(request):

    context = {}   
    groups = Group.objects.all()
    context.update({'groups': groups})

    return render(request, 'home.html', context)


def allTeachers(request):

    context = {}
    try:
        teachers = CustomUser.objects.filter(isTeacher = True)
        context.update({'teachers': teachers})

        return render(request, 'teachers.html', context)

    except:

        return render(request, 'teachers.html', context)


def allStudents(request):

    context = {}
    try:
        students = CustomUser.objects.filter(isTeacher = False)
        context.update({'students': students})

        return render(request, 'students.html', context)

    except:

        return render(request, 'students.html', context)


def groupInfo(request, groupName):

    context = {}

    user = request.user

    group = Group.objects.get(groupName = groupName)
    students = CustomUser.objects.filter(userGroup = group.id)
    groupTeacher = Group.objects.get(groupName = groupName).groupTeacher

    context.update({'students': students, 'group': group, 'groupTeacher': groupTeacher})

    try:
        studentCheck = CustomUser.objects.get(id = user.id)
        context.update({'isStudent': True})
        try:
            context.update({'requestGroup': studentCheck.userGroup.groupName})
        except:
            context.update({'requestGroup': 'ошибка'})
    except:
        context.update({'isStudent': False})

    return render(request, 'group-info.html', context)
    


def teacherInfo(request, username):

    context = {'group': False}

    # преподаватель, которому принадлежит страница
    user = CustomUser.objects.get(username = username)

    try:
        achievements = Achievement.objects.filter(person = user)
        context.update({'achievements': achievements})
        context.update({'user': user})

    except:       
        context.update({'user': user, 'teacher': False})

    try:
        group = Group.objects.get(groupTeacher = user.id)
        context['group'] = group

    except:
        pass

    if request.user.id == user.id:
        context.update({'ownProfile': True})

        if request.method == 'POST':
            form = AchievementForm(request.POST, request.FILES)       
            if form.is_valid():               
                ancet = form.save(commit=False)
                userAchievement = Achievement.objects.create(person = request.user, achievement = ancet.achievement, name = ancet.name)
                userAchievement.save()

                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            else:

                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        else:
            form = AchievementForm()
            context.update({'form': form})

            return render(request, 'teacher-info.html', context)

    return render(request, 'teacher-info.html', context)


def studentInfo(request, username):

    context = {}

    # студент, которому принадлежит страница
    try:
        user = CustomUser.objects.get(username = username)
    except:
        return render(request, 'student-info.html', context)

    try:
        studentGroup = user.userGroup
        groupTeacher = Group.objects.get(id = studentGroup.id).groupTeacher
        achievements = Achievement.objects.filter(person = user).order_by('-id')

        context.update({'achievements': achievements, 'user': user, 'studentGroup': studentGroup, 'groupTeacher': groupTeacher})
    except:
        studentGroup = False
        groupTeacher = False
        achievements = Achievement.objects.filter(person = user).order_by('-id')

        context.update({'achievements': achievements, 'user': user, 'studentGroup': studentGroup, 'groupTeacher': groupTeacher})

    if request.user.id == user.id:
        context.update({'ownProfile': True})

        if request.method == 'POST':
            form = AchievementForm(request.POST, request.FILES)       
            if form.is_valid():
                ancet = form.save(commit=False)
                userAchievement = Achievement.objects.create(person = request.user, achievement = ancet.achievement, name = ancet.name)
                userAchievement.save()
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            else:
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        else:
            form = AchievementForm()
            context.update({'form': form})
            return render(request, 'student-info.html', context)
    else:
        return render(request, 'student-info.html', context)


def joinGroup(request, groupName):

    if not request.user.is_authenticated:
        return redirect('authentication')
    else:
        user = request.user
        try:
            group = get_object_or_404(Group, groupName = groupName)
            if not user.userGroup.null:
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            else:
                user.userGroup = group
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        except Exception:
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def leaveGroup(request, groupName):
    if not request.user.is_authenticated:
        return redirect('authentication')
    else:
        user = request.user
        try:
            if not user.userGroup.null:
                user.userGroup = ''
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            else:
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        except:
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def checkAchievement(request, id):

    try:
        achievement = Achievement.objects.get(id = id)
        pdf_file = achievement.achievement.path       
        response = FileResponse(open(pdf_file, 'rb'))

        return response
    except:
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def deleteAchievement(request, id):
    if not request.user.is_authenticated:
        return redirect('authentication')
    else:
        try:
            achievement = get_object_or_404(Achievement, id = id)
            if achievement.person == request.user:
                achievement.delete()
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            else:
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        except:
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

main/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <title>{% block title %}  {% endblock %}</title>
  </head>
  <body>
    {% include 'navbar.html' %}
    {% block content %}

    {% endblock %}
    {% include 'footer.html' %}

    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'scripts.js' %}"></script>
  </body>
</html>

main/templates/footer.html
<div class="container my-5">
    <hr style="color: white">
    <footer
            class="text-center text-lg-start text-white"
            style="background-color: #212121"
            >
        <div>
          <a href="" class="text-white me-4">
            <i class="fab fa-facebook-f"></i>
          </a>
          <a href="" class="text-white me-4">
            <i class="fab fa-twitter"></i>
          </a>
          <a href="" class="text-white me-4">
            <i class="fab fa-google"></i>
          </a>
          <a href="" class="text-white me-4">
            <i class="fab fa-instagram"></i>
          </a>
          <a href="" class="text-white me-4">
            <i class="fab fa-linkedin"></i>
          </a>
          <a href="" class="text-white me-4">
            <i class="fab fa-github"></i>
          </a>
        </div>
      </section>
 
      <section class="">
        <div class="container text-center text-md-start mt-5">
          <div class="row mt-3">
            <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
              <h6 class="text-uppercase fw-bold">Название колледжа</h6>
              <hr
                  class="mb-4 mt-0 d-inline-block mx-auto"
                  style="width: 60px; background-color: #FF9800; height: 2px"
                  />
              <p>
                Отделение колледжа
              </p>
            </div>
            
            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
              <h6 class="text-uppercase fw-bold">Контакты</h6>
              <hr
                  class="mb-4 mt-0 d-inline-block mx-auto"
                  style="width: 60px; background-color: #FF9800; height: 2px"
                  />
              <p>
                <a href="mailto:tsaritsino@edu.mos.ru" class="fas fa-home me-3">фффффф@mail.ru</a>
              </p>
              <p>
                <a href="tel:+74953912333" class="fas fa-home me-3">Тел: +7(777)777-77-77</a>
              </p>
            </div>

            <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
              <h6 class="text-uppercase fw-bold">Автор</h6>
              <hr
                  class="mb-4 mt-0 d-inline-block mx-auto"
                  style="width: 60px; background-color: #FF9800; height: 2px"
                  />
              <p>
                <a href="https://collegetsaritsyno.mskobr.ru/" class="fas fa-home me-3">Адрес</a>
              </p>
              <p>
                <a href="mailto:efimo-olesya@mail.ru" class="fas fa-home me-3">sssss@mail.ru</a>
              </p>
            </div>
          </div>
        </div>
      </section>

      <div
           class="text-center p-3"
           style="background-color: rgba(0, 0, 0, 0.2)"
           >
        © 2022
      </div>
    </footer>
</div>

main/templates/group-info.html
{% extends 'base.html' %}
{% load static %}

{% block title %} {{group.groupName}} {% endblock %}

{% block content %}
    
<div class="container">
    <div class="row mx-auto">
        {% if not request.user.isTeacher %}
            {% if not isStudent %}
                <a class="join_leave mt-3 text-center btn btn-outline-dark" href="{% url 'join-group' group.groupName %}">Присоединиться ко группе</a>
            {% else %}
                <a class="join_leave mt-3 text-center btn btn-outline-dark" href="{% url 'leave-group' requestGroup %}">Вы уже вступили в группу {{requestGroup}}. Покинуть группу?</a>
            {% endif %}
        {% endif %}
        <div class="container col col-md-3 col-sm-4 mt-2 mb-5 mt-4 mb-4 p-3 d-flex justify-content-center">
            <div class="student-card card p-4">
                <div class="image d-flex flex-column justify-content-center align-items-center"> 
                    {% if groupTeacher.teacherPhoto %}
                        <img src="{{groupTeacher.teacherPhoto.url}}" class="rounded" height="100" width="100">
                    {% else %}
                        <button class="btn btn-secondary"> 
                        <img src="{% static 'images/default-photo.jpeg' %}" height="100" width="100"></button>
                    {% endif %}
                    <span class="name mt-3">{{groupTeacher.fullName}}</span>
                    <div class="d-flex flex-row justify-content-center align-items-center gap-2 mb-2 mt-3"> <span class="idd">Куратор группы</span></div>
                    <div class=" d-flex mt-2"> <a href="{% url 'teacher-info' groupTeacher.mainProfile.username %}" class="btn btnProfile">Профиль</a> </div>
                    <div class="gap-3 mt-3 icons d-flex flex-row justify-content-center align-items-center"></div>
                </div>
            </div>
        </div>
        {% for student in students %}
            <div class="container col col-md-3 col-sm-4 mt-2 mb-5 mt-4 mb-4 p-3 d-flex justify-content-center">
                <div class="student-card card p-4">
                    <div class="image d-flex flex-column justify-content-center align-items-center"> 
                        {% if student.student.avatar %}
                            <img src="{{student.student.avatar.url}}" class="rounded" height="100" width="100">
                        {% else %}
                            <button class="btn btn-secondary"> 
                            <img src="{% static 'images/default-photo.jpeg' %}" height="100" width="100"></button>
                        {% endif %}
                        <span class="name mt-3">{{student.shortName}}</span> <span class="idd">@{{student.student.username}}</span>
                        <div class="d-flex flex-row justify-content-center align-items-center gap-2"> <span class="idd1">{{student.group}}</span></div>
                        <div class=" d-flex mt-2"> <a href="{% url 'student-info' student.student.username %}" class="btn btnProfile">Профиль</a> </div>
                        <div class="gap-3 mt-3 icons d-flex flex-row justify-content-center align-items-center"></div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

main/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Заголовок {% endblock %}

{% block content %}
<div class="container">
    <div class="row mx-auto justify-content-around">
        {% for group in groups %}
        <div class="col col-md-3 col-sm-4 mt-2 mb-5">
            <div class="card group-card" style="width: 12rem;">
                <div class="card-body">
                  <a class="btn-groupName" href="{{group.get_url}}"><h4 class="card-title">{{group.groupName}}</h4></a>
                  <a class="btn-groupName" href="{{group.get_teacher}}"><h6 class="card-title">{{group.groupTeacher}}</h6></a>
                </div>
              </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

main/templates/navbar.html
<nav class="my-navbar navbar navbar-expand-sm navbar-dark bg-dark mb-3">
    <div class="container-fluid">
      <a class="navbar-brand link" href="{% url 'home' %}">Главная</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample03" aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample03">
        <ul class="navbar-nav me-auto mb-2 mb-sm-0">
          <li class="nav-item">
            {% if not request.user.isTeacher %}
              <a class="nav-link link active" aria-current="page" href="{% url 'student-info' request.user %}">Мой профиль</a>
            {% else %}
              <a class="nav-link link active" aria-current="page" href="{% url 'teacher-info' request.user.username %}">Мой профиль</a>
            {% endif %}
          </li>
          <li class="nav-item">
            <a class="nav-link link active" aria-current="page" href="{% url 'teachers' %}">Преподаватели</a>
          </li>
          <li class="nav-item">
            <a class="nav-link link active" aria-current="page" href="{% url 'students' %}">Студенты</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

main/templates/student-info.html
{% extends 'base.html' %}
{% load static %}

{% block title %} {{student.fullName}} {% endblock %}

{% block content %}
<div class="container rounded bg-white mt-5 mb-5 person-info-card">
    <div class="row">
        <div class="col-md-3 border-right">
            <div class="d-flex flex-column align-items-center text-center p-3 py-5">
                {% if student.avatar %}
                    <img class="rounded-circle mt-5" width="250px" src="{{student.avatar.url}}">{% if ownProfile %}
                    <a class="btn btn-outline-dark" href="{% url 'delete-avatar' %}">Удалить фото профиля</a>
                {% endif %}</div>
                {% else %}
                    <img class="rounded-circle mt-5" width="150px" src="{% static 'images/default-photo.jpeg' %}"></div>
                {% endif %}
        </div>
        <div class="col-md-5 border-right">
            <div class="p-3 py-5">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    {% if ownProfile %}
                        <h3 class="text-right">Мой профиль</h3><a class="btn btn-edit" href="{% url 'edit' request.user.id %}">Редактировать профиль</a>
                    {% else %}
                        <h4 class="text-right">Профиль студента</h4>
                    {% endif %}
                </div>
                <div class="row mt-2">
                    <div class="col-md-6"><label class="labels">Имя</label><h4>{{student.first_name}}</h4></div>
                    <div class="col-md-6"><label class="labels">Фамилия</label><h4>{{student.last_name}}</h4></div>
                </div>
                <div class="row mt-3">
                    <div class="col-md-12"><label class="labels">Электронная почта</label><h4>{{student.email}}</h4></div>
                </div>
                {% if ownProfile %}
                    <div class="mt-3 text-center"><a class="open-popup" type="button"><i class="cart-icon material-icons">add</i> Добавить достижение</a></div>
                    {% if not form.is_valid %}
                    <div class="popup__bg">
                        <form class="popup" enctype="multipart/form-data" method="post" id="achievement_form">
                            {% csrf_token %}
                            <svg class="close-popup" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#3500D3" d="M23.954 21.03l-9.184-9.095 9.092-9.174-2.832-2.807-9.09 9.179-9.176-9.088-2.81 2.81 9.186 9.105-9.095 9.184 2.81 2.81 9.112-9.192 9.18 9.1z"/></svg>
                            <label>
                                <input type="file" name="achievement" required id="id_achievement">                                
                                <div class="label__text">
                                    Ваше достижение
                                </div>
                            </label>
                            {% if form.errors.achievement %}
                                <ul class="error-list">
                                    {{form.errors.achievement}}
                                </ul>
                            {% endif %}
                            <label>
                                <textarea name="name" cols="40" rows="10" class="vLargeTextField" maxlength="127" required="" id="id_name"></textarea>
                                <div class="label__text">
                                    Название мероприятия/соревнования
                                </div>
                            </label>
                            {% if form.errors.name %}
                                <ul class="error-list">
                                    {{form.errors.name}}
                                </ul>
                            {% endif %}
                            <input type="submit" value="Добавить" name="_save">
                        </form>
                    </div> 
                    {% endif %} 
                {% endif %}
            </div>
        </div>
        <div class="col-md-4">
            <div class="p-3 py-5">
                {% if studentGroup %}
                    <div class="col-md-12"><label class="labels">Номер группы</label><h3><a href="{{studentGroup.get_url}}">{{studentGroup.groupName}}</a></h3></div> <br>
                    <div class="col-md-12"><label class="labels">Куратор группы</label><h3><a href="{{studentGroup.get_teacher}}">{{groupTeacher.groupTeacher}}</a></h3></div>
                {% else %}
                    <div class="col-md-12"><label class="labels">Номер группы</label><h3><a href="{% url 'home' %}">К списку групп <i class="cart-icon material-icons">chevron_right</i></a></h3></div> <br>
                    <div class="col-md-12"><label class="labels">Куратор группы</label><h3><p>Вы не вступили в группу</p></h3></div>
                {% endif %}
            </div>
        </div>
        <hr>
        <div class="album py-5">
            <div class="container">
                <div class="row">
                  {% for achievement in achievements %}
                  <div class="col-md-4">
                    <div class="achievement card mb-4 shadow-sm">
                        <div class="card-body">
                            <p class="card-text"><a href="{% url 'check-achievement' achievement.id %}" target="_blank">{{ achievement.name }}</a></p>
                            <small>
                                {% if ownProfile %}<a href="{% url 'delete-achievement' achievement.id %}"><i class="cart-icon material-icons">delete</i></a></small>{% endif %}
                        </div>
                    </div>
                  </div>
                  {% endfor %}
                </div>
          </div>
        </div>
    </div>
</div>


{% endblock %}

main/templates/students.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Студенты колледжа {% endblock %}

{% block content %}

<div class="container">
    <div class="row mx-auto">
        {% for student in students %}
            <div class="container col col-md-3 col-sm-4 mt-2 mb-5 mt-4 mb-4 p-3 d-flex justify-content-center">
                <div class="student-card card p-4">
                    <div class="image d-flex flex-column justify-content-center align-items-center"> 
                        {% if student.student.avatar %}
                            <img src="{{student.student.avatar.url}}" class="rounded" height="100" width="100">
                        {% else %}
                            <button class="btn btn-secondary"> 
                            <img src="{% static 'images/default-photo.jpeg' %}" height="100" width="100"></button>
                        {% endif %}
                        <span class="name mt-3">{{student.shortName}}</span> <span class="idd">@{{student.student.username}}</span>
                        <div class="d-flex flex-row justify-content-center align-items-center gap-2"> <span class="idd1">{{student.group}}</span></div>
                        <div class=" d-flex mt-2"> <a href="{% url 'student-info' student.student.username %}" class="btn btnProfile">Профиль</a> </div>
                        <div class="gap-3 mt-3 icons d-flex flex-row justify-content-center align-items-center"></div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

main/templates/teacher-info.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Преподаватель - {{teacher.fullName}} {% endblock %}

{% block content %}
<div class="container rounded bg-white mt-5 mb-5 person-info-card">
    <div class="row">
        <div class="col-md-3 border-right">
            <div class="d-flex flex-column align-items-center text-center p-3 py-5">
                {% if teacher.avatar %}
                    <img class="rounded-circle mt-5" width="250px" src="{{teacher.teacherPhoto.url}}"></div>
                    <a class="btn btn-outline-dark" href="{% url 'delete-avatar' %}">Удалить фото профиля</a>
                {% else %}
                    <img class="rounded-circle mt-5" width="150px" src="{% static 'images/default-photo.jpeg' %}"></div>
                {% endif %}
        </div>
        <div class="col-md-5 border-right">
            <div class="p-3 py-5">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    {% if request.user == user %}
                        <h4 class="text-right">Мой профиль</h4><a class="btn btn-edit" href="{% url 'edit' request.user.id %}">Редактировать профиль</a>
                    {% else %}
                        <h4 class="text-right">Профиль преподавателя</h4>
                    {% endif %}
                </div>
                <div class="row mt-2">
                    <div class="col-md-6"><label class="labels">Фамилия</label><h4>{{user.last_name}}</h4></div>
                    <div class="col-md-6"><label class="labels">Имя</label><h4>{{user.first_name}}</h4></div>
                    <div class="col-md-6"><label class="labels">Отчество</label><h4>{{teacher.teacherPatronymic}}</h4></div>
                </div>
                <div class="row mt-3">
                    <div class="col-md-12"><label class="labels">Электронная почта</label><h4>{{user.email}}</h4></div>
                </div>
                {% if ownProfile %}
                    <div class="mt-3 text-center"><a class="open-popup" type="button"><i class="cart-icon material-icons">add</i> Добавить достижение</a></div>
                    {% if not form.is_valid %}
                    <div class="popup__bg">
                        <form class="popup" enctype="multipart/form-data" method="post" id="achievement_form">
                            {% csrf_token %}
                            <svg class="close-popup" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#3500D3" d="M23.954 21.03l-9.184-9.095 9.092-9.174-2.832-2.807-9.09 9.179-9.176-9.088-2.81 2.81 9.186 9.105-9.095 9.184 2.81 2.81 9.112-9.192 9.18 9.1z"/></svg>
                            <label>
                                <input type="file" name="achievement" required id="id_achievement">                                
                                <div class="label__text">
                                    Ваше достижение
                                </div>
                            </label>
                            {% if form.errors.achievement %}
                                <ul class="error-list">
                                    {{form.errors.achievement}}
                                </ul>
                            {% endif %}
                            <label>
                                <textarea name="name" cols="40" rows="10" class="vLargeTextField" maxlength="127" required="" id="id_name"></textarea>
                                <div class="label__text">
                                    Название
                                </div>
                            </label>
                            {% if form.errors.name %}
                                <ul class="error-list">
                                    {{form.errors.name}}
                                </ul>
                            {% endif %}
                            <input type="submit" value="Добавить" name="_save">
                        </form>
                    </div> 
                    {% endif %} 
                {% endif %}
            </div>
        </div>
        <div class="col-md-4">
            <div class="p-3 py-5">
                {% if group %}
                    <div class="col-md-12"><label class="labels">Куратор группы</label><h3><a href="{{group.get_url}}">{{group.groupName}}</a></h3></div> <br>
                    <div class="col-md-12"><label class="labels">Предметы</label><h3>{{teacher.teacherSubjects}}</h3></div>
                {% else %}
                    <div class="col-md-12"><label class="labels">Предметы</label><h3>{{teacher.teacherSubjects}}</h3></div>
                {% endif %}
            </div>
        </div>
        <hr>
        <div class="album py-5">
            <div class="container">
                <div class="row">
                  {% for achievement in achievements %}
                  <div class="col-md-4">
                    <div class="achievement card mb-4 shadow-sm">
                        <div class="card-body">
                            <p class="card-text"><a href="{% url 'check-achievement' achievement.id %}" target="_blank">{{ achievement.name }}</a></p>
                            <small>
                                {% if ownProfile %}<a href="{% url 'delete-achievement' achievement.id %}"><i class="cart-icon material-icons">delete</i></a></small>{% endif %}
                        </div>
                    </div>
                  </div>
                  {% endfor %}
                </div>
          </div>
        </div>
    </div>
</div>
{% endblock %}